PUT http://localhost:8081/v1/organization/abcd/license
Accept-Language: es
Content-Type: application/json

{
    "id": 1,
    "licenseId": "anfohson",
    "description": "First license",
    "productName": "Software Product",
    "licenseType": "Enterprises"
}


### Get license using organization id and license id
GET localhost:8080/v1/organization/d898a142-de44-466c-8c88-9ceb2c2429d3/license/f2a9c9d4-d2c0-44fa-97fe-724d77173c62